### ISSUE TITLE
mpy zips don't contain mpy files

### ISSUE THREAD

**Issue by FoamyGuy** [adafruit/Adafruit_CircuitPython_Typing#34]
The assets on the release page that are supposed to contain mpy files for the library don't actually contain library files. Instead they contain only the examples:

![image](https://github.com/adafruit/Adafruit_CircuitPython_Typing/assets/2406189/e6d3fcaa-d756-47ef-bcbd-06171a55bf8a)

This library is not typically used on devices so it's unlikely many people would be looking for it there, I guess that is why it has gone undiscovered. 

I ran across a need to put it on a device to check something and noticed I'm unable to install it circup or grab the mpy files manually from the release assets.

**Comment by Neradoc** [comment]
The absence of the mpy files seems to be due to a bug in the new action thing, where packages without the adafruit_ prefix are ignored. I'll open an issue for that.

However, I believe the fix here is simply to disable the workflow that creates those zips.
This library should not be used on devices, its absence MUST trigger the `except` clause in libraries that try to import it it.

In fact it can't be compiled with mpy-cross:
```
❯ mpy-cross circuitpython_typing/io.py 
Traceback (most recent call last):
  File "circuitpython_typing/io.py", line 43
SyntaxError: invalid syntax
```

**Comment by tekktrik** [comment]
I can add a disabling input for the workflow, I agree that makes the most sense.  It should only disable `.mpy` zip(s), right?

**Comment by tekktrik** [comment]
Alright, ready to make a PR for this!
